// <auto-generated />
namespace Autheriz_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CreatTableforidentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatTableforidentity));
        
        string IMigrationMetadata.Id
        {
            get { return "202506130650433_Creat Table for identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
